baseURL = "https://consultationkit.com"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Consultation Kit"
theme = "berawa"
publishDir = "docs"

[Params]
  calendarId = "a33e54a0-1fee-11e7-b74a-0e9b8b43f288"
  txFee = "2.5"
  custom_css = ["css/main.css"]
  # primary logo
  logo = "img/logo.png"
  coverImg = "img/bg.jpg"
  # img pointing to calendar
  calloutImg = "img/try-callout.png"
  # Header Text
  intro = "Convert your online traffic into paying customers"
  introTagline = "No hassle consultation bookings. Get paid up front for your time. Leave the meeting logistics to us."

[Author]
  name = "First Bird Labs"
  email = "info@consultationkit.com"

[[menu.main]]
    name = "How It Works"
    url = "/#how-it-works"
    weight = 1

[[menu.main]]
    name = "Plan Info"
    url = "/#plans"
    weight = 2

[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 3

[[menu.main]]
    name = "Login"
    url = "https://dashboard.consultationkit.com"
    weight = 4
